### ISSUE TITLE
Using GitLab and Anka Build Cloud

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [veertuinc/anka-docs#42]
Hi

I think there is a missing image in the end of [this section](https://ankadocs.veertu.com/docs/ci-plugins-and-integrations/gitlab/#registration):

> You should now see the runner in your GitLab:
> gitlab runner attached

With the image url https://ankadocs.veertu.com/images/gitlab-runner-attached.png

Best regards
Jens

**Comment by NorseGaud** [comment]
Fixing, thanks!
