### ISSUE TITLE
Template vs VM

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [veertuinc/anka-docs#45]
Hi

I'm confused about the difference between a template and a VM.

In [this part of the documentation](https://ankadocs.veertu.com/docs/getting-started/creating-your-first-vm/), template is used all over the place e.g. 
> You can create Templates using anka create

But in the commands documentation VM is [used](https://ankadocs.veertu.com/docs/anka-build-cloud/virtualization-cli/command-reference/#create)
> Creates a VM

I think you could be a lot clearer on the difference (if any?) between template and VM. 

Best regards
Jens

**Comment by NorseGaud** [comment]
Hey Jens, our CLI will be getting different help messages soon to fix that. It'll be released in the next version in the coming weeks.

To clarify: VM Templates are an image/snapshot of a certain OS either stopped or in a suspended state. When you use `anka start`, you're starting a VM Template to create a running VM. 

Thanks for the feedback!
