### ISSUE TITLE
Discrepency in Licensing docs

### ISSUE THREAD

**Issue by mariobrostech** [veertuinc/anka-docs#57]
Hi,

While your documentation and official website state multiple times that Anka Develop is only licensed freely on MacBooks, some parts of the documentation don't reflect this. For example, [this product matrix](https://docs.veertu.com/anka/licensing/#anka-virtualization) highlights Develop as also being licensed for iMacs, which anecdotal evidence suggests isn't the case. Can you please clear up this language to make it more obvious where Anka Develop is and isn't permitted to be used?

Thank you in advance!

**Comment by NorseGaud** [comment]
Hi @mariobrostech , thanks for the ticket and for taking the time to submit it. You're right and I'll be pushing a fix for this shortly.
