### ISSUE TITLE
How are these docs built?

### ISSUE THREAD

**Issue by wmehilos** [veertuinc/anka-docs#61]
Sorry if this is the wrong place to ask this, but I really like how these docs look and I was curious what SSG and theme you were using. I'm guessing the repo here is just the "content" directory of a Hugo site but I'm not totally sure, and I'd love to know what theme you're all using if it's one that's public/open source. 

Just a curiosity, thanks in advance!

**Comment by NorseGaud** [comment]
Hey @wmehilos , you're right about hugo! We've got a modified fork of docsy you can take a look at https://github.com/veertuinc/docsy

Let me know if you have any questions
