### ISSUE TITLE
"Anka view/Anka start -v" cannot open VM display

### ISSUE THREAD

**Issue by kkkbbb** [veertuinc/anka-docs#78]
I can't open VM dispaly by "anka view/anka start -v" and  It seems like vnc is not turned on.
when I enter "anka view" no respond
os: macos 13.01
machine: m1 pro
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/18513551/203473780-a24545e7-7f3f-43df-b01d-72672891857f.png">

**Comment by NorseGaud** [comment]
@kkkbbb VNC is only enabled by default when using anka create from the command line. Creating a VM from the app will not install macOS and you'll have to open it and go through the setup process manually. Please refer to our documentation for information on creating VMs

**Comment by kkkbbb** [comment]
Tanks
